name: CI

on:
  push:
    branches:
      - main
env:
  REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        BRANCH: gh-pages
        FOLDER: build
